name: MinecraftDungeons
version: '1.0-SNAPSHOT'
main: de.fleaqx.minecraftDungeons.MinecraftDungeons
api-version: '1.21'
softdepend:
  - ProtocolLib
commands:
  zone:
    description: Zone menu and admin
    usage: /zone [max|balance|admin]
  dungeon:
    description: Dungeon debug command
    usage: /dungeon <reload|start|enchant|perk|companion>
    permission: minecraftdungeons.admin
  pay:
    description: Pay souls/essence/shards to another player
    usage: /pay <player> <souls|essence|shards> <amount>
permissions:
  minecraftdungeons.admin:
    default: op

  minecraftdungeons.companions.extra.1:
    default: false
  minecraftdungeons.companions.extra.2:
    default: false
  minecraftdungeons.companions.extra.3:
    default: false
